### ISSUE TITLE
Missing namespaces or files

### ISSUE THREAD

**Issue by vailshnast** [UnioGame/UniGame.AssetsBookmarks#1]
![image](https://github.com/UnioGame/UniGame.AssetsBookmarks/assets/23454812/31556cf3-47d8-4cc3-a1e2-165f2b48204f)
![image](https://github.com/UnioGame/UniGame.AssetsBookmarks/assets/23454812/259ce82e-8b2a-4321-a7ac-e6770721bf97)
![image](https://github.com/UnioGame/UniGame.AssetsBookmarks/assets/23454812/0417b194-e41d-4b6d-ac88-f23fd181e017)

Unity 2022.2.8

Seems like there are missing files

**Comment by Mefodei** [comment]
fixed
